---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: README.md
  label: Readme
  match: "**/*"
  read_only: true
- type: document
  path: _data/presenters.yaml
  label: Program Participant Listings
- type: document
  path: readme.md
  label: How to use Forestry
  read_only: true
- type: document
  path: _data/dealers.yaml
  label: Dealer Listings
- type: document
  path: _data/artists.yaml
  label: Artist Listings
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
